services:

  api:
    build: .
    container_name: organo_api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:17
    container_name: organo_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - organo_database:/var/lib/postgresql/data

volumes:
  organo_database: